<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scip.proto

namespace Scip;

if (false) {
    /**
     * This class is deprecated. Use Scip\Descriptor\Suffix instead.
     * @deprecated
     */
    class Descriptor_Suffix {}
}
class_exists(Descriptor\Suffix::class);
@trigger_error('Scip\Descriptor_Suffix is deprecated and will be removed in the next major release. Use Scip\Descriptor\Suffix instead', E_USER_DEPRECATED);

