<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scip.proto

namespace Scip;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scip.Descriptor</code>
 */
class Descriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string disambiguator = 2;</code>
     */
    protected $disambiguator = '';
    /**
     * NOTE: If you add new fields here, make sure to update the prepareSlot()
     * function responsible for parsing symbols.
     *
     * Generated from protobuf field <code>.scip.Descriptor.Suffix suffix = 3;</code>
     */
    protected $suffix = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $disambiguator
     *     @type int $suffix
     *           NOTE: If you add new fields here, make sure to update the prepareSlot()
     *           function responsible for parsing symbols.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string disambiguator = 2;</code>
     * @return string
     */
    public function getDisambiguator()
    {
        return $this->disambiguator;
    }

    /**
     * Generated from protobuf field <code>string disambiguator = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisambiguator($var)
    {
        GPBUtil::checkString($var, True);
        $this->disambiguator = $var;

        return $this;
    }

    /**
     * NOTE: If you add new fields here, make sure to update the prepareSlot()
     * function responsible for parsing symbols.
     *
     * Generated from protobuf field <code>.scip.Descriptor.Suffix suffix = 3;</code>
     * @return int
     */
    public function getSuffix()
    {
        return $this->suffix;
    }

    /**
     * NOTE: If you add new fields here, make sure to update the prepareSlot()
     * function responsible for parsing symbols.
     *
     * Generated from protobuf field <code>.scip.Descriptor.Suffix suffix = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSuffix($var)
    {
        GPBUtil::checkEnum($var, \Scip\Descriptor\Suffix::class);
        $this->suffix = $var;

        return $this;
    }

}

