<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scip.proto

namespace Scip;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents a diagnostic, such as a compiler error or warning, which should be
 * reported for a document.
 *
 * Generated from protobuf message <code>scip.Diagnostic</code>
 */
class Diagnostic extends \Google\Protobuf\Internal\Message
{
    /**
     * Should this diagnostic be reported as an error, warning, info, or hint?
     *
     * Generated from protobuf field <code>.scip.Severity severity = 1;</code>
     */
    protected $severity = 0;
    /**
     * (optional) Code of this diagnostic, which might appear in the user interface.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * Message of this diagnostic.
     *
     * Generated from protobuf field <code>string message = 3;</code>
     */
    protected $message = '';
    /**
     * (optional) Human-readable string describing the source of this diagnostic, e.g.
     * 'typescript' or 'super lint'.
     *
     * Generated from protobuf field <code>string source = 4;</code>
     */
    protected $source = '';
    /**
     * Generated from protobuf field <code>repeated .scip.DiagnosticTag tags = 5;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $severity
     *           Should this diagnostic be reported as an error, warning, info, or hint?
     *     @type string $code
     *           (optional) Code of this diagnostic, which might appear in the user interface.
     *     @type string $message
     *           Message of this diagnostic.
     *     @type string $source
     *           (optional) Human-readable string describing the source of this diagnostic, e.g.
     *           'typescript' or 'super lint'.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scip::initOnce();
        parent::__construct($data);
    }

    /**
     * Should this diagnostic be reported as an error, warning, info, or hint?
     *
     * Generated from protobuf field <code>.scip.Severity severity = 1;</code>
     * @return int
     */
    public function getSeverity()
    {
        return $this->severity;
    }

    /**
     * Should this diagnostic be reported as an error, warning, info, or hint?
     *
     * Generated from protobuf field <code>.scip.Severity severity = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeverity($var)
    {
        GPBUtil::checkEnum($var, \Scip\Severity::class);
        $this->severity = $var;

        return $this;
    }

    /**
     * (optional) Code of this diagnostic, which might appear in the user interface.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * (optional) Code of this diagnostic, which might appear in the user interface.
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Message of this diagnostic.
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Message of this diagnostic.
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * (optional) Human-readable string describing the source of this diagnostic, e.g.
     * 'typescript' or 'super lint'.
     *
     * Generated from protobuf field <code>string source = 4;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * (optional) Human-readable string describing the source of this diagnostic, e.g.
     * 'typescript' or 'super lint'.
     *
     * Generated from protobuf field <code>string source = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .scip.DiagnosticTag tags = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated .scip.DiagnosticTag tags = 5;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Scip\DiagnosticTag::class);
        $this->tags = $arr;

        return $this;
    }

}

