<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scip.proto

namespace Scip;

use UnexpectedValueException;

/**
 * Protobuf type <code>scip.DiagnosticTag</code>
 */
class DiagnosticTag
{
    /**
     * Generated from protobuf enum <code>UnspecifiedDiagnosticTag = 0;</code>
     */
    const UnspecifiedDiagnosticTag = 0;
    /**
     * Generated from protobuf enum <code>Unnecessary = 1;</code>
     */
    const Unnecessary = 1;
    /**
     * Generated from protobuf enum <code>Deprecated = 2;</code>
     */
    const Deprecated = 2;

    private static $valueToName = [
        self::UnspecifiedDiagnosticTag => 'UnspecifiedDiagnosticTag',
        self::Unnecessary => 'Unnecessary',
        self::Deprecated => 'Deprecated',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

