<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scip.proto

namespace Scip;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Index represents a complete SCIP index for a workspace this is rooted at a
 * single directory. An Index message payload can have a large memory footprint
 * and it's therefore recommended to emit and consume an Index payload one field
 * value at a time. To permit streaming consumption of an Index payload, the
 * `metadata` field must appear at the start of the stream and must only appear
 * once in the stream. Other field values may appear in any order.
 *
 * Generated from protobuf message <code>scip.Index</code>
 */
class Index extends \Google\Protobuf\Internal\Message
{
    /**
     * Metadata about this index.
     *
     * Generated from protobuf field <code>.scip.Metadata metadata = 1;</code>
     */
    protected $metadata = null;
    /**
     * Documents that belong to this index.
     *
     * Generated from protobuf field <code>repeated .scip.Document documents = 2;</code>
     */
    private $documents;
    /**
     * (optional) Symbols that are referenced from this index but are defined in
     * an external package (a separate `Index` message). Leave this field empty
     * if you assume the external package will get indexed separately. If the
     * external package won't get indexed for some reason then you can use this
     * field to provide hover documentation for those external symbols.
     *
     * Generated from protobuf field <code>repeated .scip.SymbolInformation external_symbols = 3;</code>
     */
    private $external_symbols;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Scip\Metadata $metadata
     *           Metadata about this index.
     *     @type array<\Scip\Document>|\Google\Protobuf\Internal\RepeatedField $documents
     *           Documents that belong to this index.
     *     @type array<\Scip\SymbolInformation>|\Google\Protobuf\Internal\RepeatedField $external_symbols
     *           (optional) Symbols that are referenced from this index but are defined in
     *           an external package (a separate `Index` message). Leave this field empty
     *           if you assume the external package will get indexed separately. If the
     *           external package won't get indexed for some reason then you can use this
     *           field to provide hover documentation for those external symbols.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scip::initOnce();
        parent::__construct($data);
    }

    /**
     * Metadata about this index.
     *
     * Generated from protobuf field <code>.scip.Metadata metadata = 1;</code>
     * @return \Scip\Metadata|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Metadata about this index.
     *
     * Generated from protobuf field <code>.scip.Metadata metadata = 1;</code>
     * @param \Scip\Metadata $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Scip\Metadata::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Documents that belong to this index.
     *
     * Generated from protobuf field <code>repeated .scip.Document documents = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDocuments()
    {
        return $this->documents;
    }

    /**
     * Documents that belong to this index.
     *
     * Generated from protobuf field <code>repeated .scip.Document documents = 2;</code>
     * @param array<\Scip\Document>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDocuments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scip\Document::class);
        $this->documents = $arr;

        return $this;
    }

    /**
     * (optional) Symbols that are referenced from this index but are defined in
     * an external package (a separate `Index` message). Leave this field empty
     * if you assume the external package will get indexed separately. If the
     * external package won't get indexed for some reason then you can use this
     * field to provide hover documentation for those external symbols.
     *
     * Generated from protobuf field <code>repeated .scip.SymbolInformation external_symbols = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExternalSymbols()
    {
        return $this->external_symbols;
    }

    /**
     * (optional) Symbols that are referenced from this index but are defined in
     * an external package (a separate `Index` message). Leave this field empty
     * if you assume the external package will get indexed separately. If the
     * external package won't get indexed for some reason then you can use this
     * field to provide hover documentation for those external symbols.
     *
     * Generated from protobuf field <code>repeated .scip.SymbolInformation external_symbols = 3;</code>
     * @param array<\Scip\SymbolInformation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExternalSymbols($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Scip\SymbolInformation::class);
        $this->external_symbols = $arr;

        return $this;
    }

}

