<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scip.proto

namespace Scip;

if (false) {
    /**
     * This class is deprecated. Use Scip\SymbolInformation\Kind instead.
     * @deprecated
     */
    class SymbolInformation_Kind {}
}
class_exists(SymbolInformation\Kind::class);
@trigger_error('Scip\SymbolInformation_Kind is deprecated and will be removed in the next major release. Use Scip\SymbolInformation\Kind instead', E_USER_DEPRECATED);

