<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9f27849cb28a3bc36461d153ef0f5435
{
    public static $files = array (
        '6124b4c8570aa390c21fafd04a26c69f' => __DIR__ . '/..' . '/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
        'f18891064a6bfacc1e06400ecc4fb7b1' => __DIR__ . '/../..' . '/src/file1.php',
        '55683e18cc9d9e9c671341a9fa5d2651' => __DIR__ . '/../..' . '/src/file2.php',
    );

    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TestDataTests\\' => 14,
        ),
        'D' => 
        array (
            'DeepCopy\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TestDataTests\\' => 
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'DeepCopy\\' => 
        array (
            0 => __DIR__ . '/..' . '/myclabs/deep-copy/src/DeepCopy',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'TestData1\\ClassA' => __DIR__ . '/../..' . '/src/ClassA.php',
        'TestData1\\ClassB' => __DIR__ . '/../..' . '/src/ClassB.php',
        'TestData2\\ClassA' => __DIR__ . '/../..' . '/src/ClassA.php',
        'TestData2\\ClassC' => __DIR__ . '/../..' . '/src/ClassA.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9f27849cb28a3bc36461d153ef0f5435::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9f27849cb28a3bc36461d153ef0f5435::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9f27849cb28a3bc36461d153ef0f5435::$classMap;

        }, null, ClassLoader::class);
    }
}
