<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'TestData\\ClassA' => $baseDir . '/src/ClassA.php',
    'TestData\\ClassB' => $baseDir . '/src/ClassB.php',
);
