<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'TestData1\\ClassA' => $baseDir . '/src/ClassA.php',
    'TestData1\\ClassB' => $baseDir . '/src/ClassB.php',
    'TestData2\\ClassA' => $baseDir . '/src/ClassA.php',
    'TestData2\\ClassC' => $baseDir . '/src/ClassA.php',
);
